version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run: 
          name: Install
          command: npm install
      - run: 
          name: Build
          command: npx @11ty/eleventy
      - run: 
          name: Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"    
workflows:
  build_and_test:
    jobs:
      - build
  
